language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: LRG3vJJKLD5lA5oesOQGSTNMLsoNylmrJmo6KiVQVK46czxhhndChhv1UjcC4c0phhIlF3RWYo7rHPi5RYll8P6Ahjhd9H+Z8h3ilT52iwhT5JJdTNzo5FgWaz6bVB1ah+72P6xscdU2wzpeHONHGPO7LjwTO8Unmp2+9utIoK0yhWAGoVuCQ6wjS0pc+42lh57DCw7a84YaNz3IK43H5hzfUh2ToGX7YRnZubVP+guxD38nYv1ihnW8RftI2ouwTXpMvOqsNHAJ0lHli0U3F/Kdct1onuy4IuPxNQeInocW/klVhOhRD/Z8quv2jmT4nACtMPRuk1LpbjFRXjAEtHDHyMhffG58+YBTPZsRgo5Re3JUB6AT1yi0i0QUfj04qmuPhW71J9Gs1UhUBXPKksYZUy5cT/S4dQawZE4q3yqVujPuUrLmD7dKYOB7g/hs56gL/4ab+fn/fvk9Pguwn4FT+ZVkE9bNUGLgs9ERzyNihBGeP4SSPo2JVBoOqdjU4A5KRyCtFu54JheStn6d2lSJiWC2ADmoZNoINxnbalQUSnH9A7tLtKeDuedP55ys8Di2n0xrTSRBXBWgZIf+pq1Oi/AYI0LJoTO2bPmwSwXONXSpU9/s7a53RJh2E8H/825ZuInQr7zEW9+/wpE8vtPSouUkaNmPsdzfRIx5bCo=
  app: https://stormy-reaches-29948.herokuapp.com/
  on:
    repo: dxtrlws/movie-app
